# Generated by Django 5.2.15 on 2026-06-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='users.program'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='explanationstep',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together={('question', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('program', 'name')},
        ),
    ]
