# Generated by Django 5.2.15 on 2026-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_curriculum_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Beginner'), ('medium', 'Intermediate'), ('hard', 'Advanced')], default='medium', max_length=10),
        ),
    ]
