# Generated by Django 5.2.15 on 2026-09-06 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_types_expected_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('faculty_approved', 'Faculty approved')], default='draft', help_text='Whether step-by-step solutions are faculty-approved for students.', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Faculty member who attested this question as mathematically sound.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionValidationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('size', models.PositiveSmallIntegerField(default=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_validation_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_sessions', to='questions.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_sessions', to='questions.topic')),
            ],
            options={
                'verbose_name': 'Question validation session',
                'verbose_name_plural': 'Question validation sessions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuestionValidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('needs_edit', 'Needs edit'), ('unpublish', 'Unpublish')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_items', to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='questions.questionvalidationsession')),
            ],
            options={
                'verbose_name': 'Question validation item',
                'verbose_name_plural': 'Question validation items',
                'ordering': ['session_id', 'order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
