# Generated by Django 5.2.17 on 2026-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_faculty_feedback_and_regenerate_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='adaptive_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Faculty-curated adaptive explanation: what_went_wrong, why, quick_check, remember, worked_example, solution_steps.'),
        ),
    ]
