# Generated by Django 5.2.17 on 2026-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_adaptive_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='adaptive_explanation_source',
            field=models.CharField(blank=True, default='', help_text="Who last wrote adaptive_explanation: 'ai' or 'faculty'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='adaptive_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Shared adaptive explanation for wrong answers: what_went_wrong, why, quick_check, remember, worked_example.'),
        ),
    ]
