# Generated by Django 5.2.15 on 2026-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_degree_program',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('bsed_math', 'BSEd Mathematics'), ('psychology', 'Psychology'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('hospitality', 'Hospitality Management'), ('criminology', 'Criminology')], default='', help_text="Student's home degree program — scopes review course offerings.", max_length=20),
        ),
    ]
