# Generated by Django 5.2.15 on 2026-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_photo_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Faculty'), ('chairperson', 'Department Chairperson')], default='student', max_length=20),
        ),
    ]
