# Generated by Django 5.2.15 on 2026-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_academicyear_alter_user_role_academicterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1),
        ),
        migrations.AlterField(
            model_name='programsection',
            name='label',
            field=models.CharField(help_text='Numeric section label, e.g. "1", "2", "3".', max_length=10),
        ),
    ]
