# Generated by Django 5.2.15 on 2026-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_exam_setup_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text='Name suffix, e.g. "Jr.", "Sr.", "III".', max_length=20),
        ),
    ]
