# Generated by Django 5.2.16 on 2026-07-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['professor', 'chairperson']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
