# Generated by Django 5.2.15 on 2026-09-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_faculty_assigned_sections_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived students are hidden from faculty rosters and cannot log in.'),
        ),
    ]
