# Generated by Django 5.2.17 on 2026-09-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignupOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email signup OTP',
                'verbose_name_plural': 'Email signup OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
