# Generated by Django 5.2.16 on 2026-07-14 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('question_generate', 'Question generate')], default='question_generate', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('course_id', models.PositiveIntegerField()),
                ('topic_id', models.PositiveIntegerField()),
                ('difficulty', models.CharField(blank=True, default='', max_length=20)),
                ('count', models.PositiveSmallIntegerField(default=3)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI generation job',
                'verbose_name_plural': 'AI generation jobs',
                'ordering': ['-created'],
            },
        ),
    ]
