# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_ai_generation_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationjob",
            name="source_material",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extracted text from faculty-uploaded learning material.",
            ),
        ),
    ]
