# Generated by Django 5.2.16 on 2026-07-24 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aigenerationjob_source_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(db_index=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, upload_to='learning_modules/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning document',
                'verbose_name_plural': 'Learning documents',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LearningChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page_start', models.PositiveIntegerField(default=1)),
                ('page_end', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.learningdocument')),
            ],
            options={
                'verbose_name': 'Learning chunk',
                'verbose_name_plural': 'Learning chunks',
                'ordering': ['document_id', 'order'],
            },
        ),
        migrations.AddField(
            model_name='aigenerationjob',
            name='learning_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='ai.learningdocument'),
        ),
    ]
