# Generated by Django 5.2.15 on 2026-09-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_aigenerationjob_question_type'),
        ('questions', '0011_system_revisions_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdocument',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningdocument',
            name='material_type',
            field=models.CharField(choices=[('module', 'Module'), ('reviewer', 'Reviewer'), ('resource', 'Learning resource'), ('exam_print', 'Printed examination material')], default='module', max_length=20),
        ),
        migrations.AddField(
            model_name='learningdocument',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_documents', to='questions.subject'),
        ),
        migrations.AddField(
            model_name='learningdocument',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
