# Generated by Django 5.2.15 on 2026-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mistake Record',
                'verbose_name_plural': 'Mistake Records',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
