# Generated by Django 5.2.15 on 2026-06-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('questions', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_record', to='reviews.answer'),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_records', to='questions.question'),
        ),
    ]
