# Generated by Django 5.2.15 on 2026-06-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Error Type',
                'verbose_name_plural': 'Error Types',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='error_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_records', to='analytics.errortype'),
        ),
    ]
