# Generated by Django 5.2.15 on 2026-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_errortype_mistakerecord_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
    ]
