# Generated by Django 5.2.16 on 2026-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_mistake_record_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='mistake_concerns/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='student_note',
            field=models.TextField(blank=True),
        ),
    ]
