# Generated by Django 5.2.16 on 2026-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_mistake_record_student_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='faculty_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mistakerecord',
            name='faculty_noted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
