# Generated by Django 5.2.15 on 2026-08-31 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_mistake_concern_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakerecord',
            name='concern_faculty',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'professor'}, related_name='concern_mistake_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
