# Generated by Django 5.2.17 on 2026-09-19 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_migrate_concern_to_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant_high', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_conversations_as_high', to=settings.AUTH_USER_MODEL)),
                ('participant_low', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_conversations_as_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Conversation',
                'verbose_name_plural': 'Faculty Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty_peer_chat/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_peer_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.facultyconversation')),
            ],
            options={
                'verbose_name': 'Faculty Message',
                'verbose_name_plural': 'Faculty Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='facultyconversation',
            constraint=models.UniqueConstraint(fields=('participant_low', 'participant_high'), name='analytics_facultyconversation_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='facultyconversation',
            constraint=models.CheckConstraint(condition=models.Q(('participant_low_id__lt', models.F('participant_high_id'))), name='analytics_facultyconversation_low_lt_high'),
        ),
    ]
