# Generated by Django 5.2.15 on 2026-06-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.reviewsession'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('session', 'question')},
        ),
    ]
