# Generated by Django 5.2.15 on 2026-06-18 16:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_explanationstep_professor_note_and_more'),
        ('reviews', '0002_initial'),
        ('users', '0002_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('allowed_difficulties', models.JSONField(default=list)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Review Window',
                'verbose_name_plural': 'Review Windows',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='StepFeedbackView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Step Feedback View',
                'verbose_name_plural': 'Step Feedback Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sessions', to='users.course'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', [1, 3, 5])), name='answer_confidence_tier'),
        ),
        migrations.AddField(
            model_name='reviewwindow',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_windows', to='users.course'),
        ),
        migrations.AddField(
            model_name='reviewwindow',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_review_windows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewwindow',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='review_windows', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='review_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='reviews.reviewwindow'),
        ),
        migrations.AddField(
            model_name='stepfeedbackview',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedback_views', to='reviews.answer'),
        ),
        migrations.AddField(
            model_name='stepfeedbackview',
            name='explanation_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedback_views', to='questions.explanationstep'),
        ),
    ]
