# Generated by Django 5.2.15 on 2026-06-28 15:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_difficulty'),
        ('reviews', '0007_alter_reviewsession_difficulty'),
        ('users', '0013_exam_setup_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='pre_session_confidence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='session_goal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True)),
                ('allowed_difficulties', models.JSONField(default=list)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setup', to='users.course')),
                ('topics', models.ManyToManyField(blank=True, related_name='exam_setups', to='questions.topic')),
            ],
            options={
                'verbose_name': 'Exam Setup',
                'verbose_name_plural': 'Exam Setups',
            },
        ),
    ]
