# Generated by Django 5.2.16 on 2026-07-25 03:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_add_midyear_semester'),
        ('reviews', '0012_reviewsession_question_queue_subjects'),
        ('users', '0017_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True)),
                ('seconds_per_question', models.PositiveIntegerField(default=30, help_text='Fallback per-question time when a course has no ExamSetup.')),
                ('allowed_difficulties', models.JSONField(default=list)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setup', to='users.programsection')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Courses students in this section may select for exams.', related_name='section_exam_setups', to='questions.subject')),
            ],
            options={
                'verbose_name': 'Section Exam Setup',
                'verbose_name_plural': 'Section Exam Setups',
            },
        ),
    ]
