# Generated by Django 5.2.15 on 2026-08-15 10:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_add_midyear_semester'),
        ('reviews', '0014_tutor_message_image'),
        ('users', '0017_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramExamSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_enabled', models.BooleanField(default=True)),
                ('seconds_per_question', models.PositiveIntegerField(default=30, help_text='Default time limit per question for student exams.')),
                ('allowed_difficulties', models.JSONField(default=list)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_setup', to='users.program')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Course subjects students may select for exams. Empty = full catalog.', related_name='program_exam_setups', to='questions.subject')),
            ],
            options={
                'verbose_name': 'Program Exam Setup',
                'verbose_name_plural': 'Program Exam Setups',
            },
        ),
    ]
