# Generated by Django 5.2.17 on 2026-09-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_system_revisions_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
